ESports/Models/Trophy.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ESports.Models
{
    public class Trophy
    {
        [Key]
        public int Id { get; set; }


        [Required]
        [DisplayName("Trophy Name")]
        public string Name { get; set; }

        [Required]
        [DisplayName("Event Venue")]
        public string Venue { get; set; }

        [Required]
        [DisplayName("Event Starting Date")]
        public DateTime StartDate { get; set; }

        [Required]
        [DisplayName("Event Ending Date")]
        public DateTime EndDate { get; set; }

        [Required]
        [DisplayName("Registration/Bidding Closing Date")]
        public DateTime ClosingDate { get; set; } 

        public DateTime CreatedDateTime { get; set; } = DateTime.Now;

        public Boolean isClosed { get; set; } = false;
    }
}

ESports/Controllers/BidController.cs
using ESports.Data;
using ESports.Models;
using identityRoleBased.Models.Domain;
using Microsoft.AspNetCore.Mvc;

namespace ESports.Controllers
{
    public class BidController : Controller
    {
        private readonly AppDbContext _db;
        private readonly DatabaseContext _userdb;

        public BidController(AppDbContext db, DatabaseContext userdb)
        {
            _db = db;
            _userdb = userdb;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TrophyDetailsViewModel details)
        {
            var teamold = _db.Teams.FirstOrDefault(a => a.Name == details.team);
            var team = _userdb.Users.FirstOrDefault(a => a.UserName == details.team);
            if (team != null)
            {
                var dbTeam = _db.TrophyTeams.FirstOrDefault(a => a.TeamId == team.Id);
                var spent = 0;
                var max = 0;
                if (dbTeam != null) { spent = dbTeam.SpentAmount; max = dbTeam.MaxPrice; }
                if (spent < max)
                {
                    var teamId = team.Id;
                    PlayersBid bidRecord = new PlayersBid();
                    bidRecord.TeamId = teamId;
                    bidRecord.BidAmount = details.bidValue;
                    bidRecord.TrophyID = details.trophyId;
                    //bidRecord.PlayerId = int.Parse(details.registrations[0].PlayerNIC);
                    bidRecord.PlayerId = int.Parse(details.playerNIC);
                    spent += dbTeam.SpentAmount;
                    if (dbTeam != null) { dbTeam.SpentAmount = spent; _db.TrophyTeams.Add(dbTeam); }
                    
                    _db.PlayersBids.Add(bidRecord);
                    try { 
                        _db.SaveChanges();
                    }catch(Exception e)
                    {
                        return StatusCode(400, e.ToString());
                    }


                }


                return RedirectToAction("Index", "Trophy");
            }
            else
            {
                return Content(details.team);
            }

        }
    }
}

ESports/Controllers/PlayerController.cs
using ESports.Data;
using ESports.Models;
using Microsoft.AspNetCore.Mvc;

namespace ESports.Controllers
{
    public class PlayerController : Controller
    {
        private readonly AppDbContext _db;
        public PlayerController(AppDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var playerList = _db.TrophyRegistrations.ToList().DistinctBy(a => a.PlayerNIC).ToList();


            if (playerList != null)
            {
                return View(playerList);

            }
            return RedirectToAction("Index", "Trophy");
        }

        public IActionResult Profile(string nic)
        {
            var player = _db.TrophyRegistrations.Where(a => a.PlayerNIC == nic).ToList();
            List<Trophy> appliedTrophies = new List<Trophy>();

            foreach (var item in player)
            {
                var trophy = _db.Trophies.Find(item.TrophyID);
                if (trophy != null)
                {
                    appliedTrophies.Add(trophy);
                }
            }

            ProfileViewModel profiles = new ProfileViewModel();
            profiles.registrations = player;
            profiles.trophies = appliedTrophies;

            return View(profiles);
        }
    }
}

ESports/Controllers/RegistrationController.cs
using ESports.Data;
using ESports.Models;
using Microsoft.AspNetCore.Mvc;

namespace ESports.Controllers
{
    public class RegistrationController : Controller
    {
        private readonly AppDbContext _db;
        public RegistrationController(AppDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Enroll(string tid)
        {
            EnrollViewModel enrollModel = new EnrollViewModel();

            TrophyRegistration trophyregistration = new TrophyRegistration();
            Trophy trophy = new Trophy();

            trophyregistration.TrophyID = int.Parse(tid);

            int trophyid = int.Parse(tid);
            trophy.Id = trophyid;
            var getTrophy = _db.Trophies.Find(trophyid);
            if (getTrophy != null)
            {
                trophy.Name = getTrophy.Name;
            }
            else
            {
                trophy.Name = "N/A";
            }

            enrollModel.TrophyRegistration = trophyregistration;
            enrollModel.Trophy = trophy;

            return View(enrollModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Enroll(EnrollViewModel enrollData)
        {
            var recordExists = _db.TrophyRegistrations.Find(enrollData.TrophyRegistration.TrophyID, enrollData.TrophyRegistration.PlayerNIC);
            if (recordExists == null)
            {
                _db.TrophyRegistrations.Add(enrollData.TrophyRegistration);
                
            }
            else
            {
                return RedirectToAction("Index", "Trophy");
            }
            //enrollData.TrophyRegistration.Player = enrollData.Player;
            
            _db.TrophyRegistrations.Add(enrollData.TrophyRegistration);
            _db.SaveChanges();
            return RedirectToAction("Index","Trophy");
        }
    }
}

ESports/Controllers/TrophyController.cs
using ESports.Data;
using ESports.Models;
using Microsoft.AspNetCore.Mvc;

namespace ESports.Controllers
{
    public class TrophyController : Controller
    {

        private readonly AppDbContext _db;
        public TrophyController(AppDbContext db)
        {
            _db = db;
        }

        // this will display list of all Tropies
        public IActionResult Index()
        {
            IEnumerable<Trophy> objCategoryList = _db.Trophies;
            return View(objCategoryList);
        }

        // to direct to create a new Trophy page
        public IActionResult Create()
        {
            return View();
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Trophy obj)
        {
            if (ModelState.IsValid)
            {
                _db.Trophies.Add(obj);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(obj);
        }

        // GET
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var trophyFromDb = _db.Trophies.Find(id);

            if (trophyFromDb == null)
            {
                return NotFound();
            }

            return View(trophyFromDb);
        }

        public IActionResult Details(int tid)
        {
            var trophy = _db.Trophies.Find(tid);
            if (trophy != null)
            {
                var playerList = _db.TrophyRegistrations.Where(a => a.TrophyID == trophy.Id).ToList();
                TrophyDetailsViewModel trophyDetails = new TrophyDetailsViewModel();
                trophyDetails.trophy = trophy;
                trophyDetails.registrations = playerList;



                return View(trophyDetails);
            }
            else
            {
                return RedirectToAction("Index", "Trophy");
            }
        }
        [HttpPost]
        public IActionResult Details()
        {
            return View();
        }


        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Trophy obj)
        {
            if (ModelState.IsValid)
            {
                _db.Trophies.Update(obj);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(obj);
        }

        // GET
        public IActionResult Close(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var trophyFromDb = _db.Trophies.Find(id);

            if (trophyFromDb == null)
            {
                return NotFound();
            }

            return View(trophyFromDb);
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Close(int id)
        {
            var trophyFromDb = _db.Trophies.Find(id);
            if (trophyFromDb == null)
            {
                return NotFound();
            }
        
                trophyFromDb.isClosed = true;
                _db.SaveChanges();

                return RedirectToAction("Index");
           
           
        }

        // GET
        public IActionResult Update(string? id, int? tid)
        {
          IEnumerable<TrophyRegistration> objCategoryList = _db.TrophyRegistrations;
            if (id == null || tid == 0)
            {
                return NotFound();
            }
            var trophyFromDb = _db.TrophyRegistrations.FirstOrDefault(a => a.TrophyID == tid && a.PlayerNIC == id);

            if (trophyFromDb == null)
            {
                return NotFound();
            }

            return View(trophyFromDb);
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdatePOST(TrophyRegistration updatedTrophy)
        {

             var trophyFromDb = _db.TrophyRegistrations.FirstOrDefault(a => a.TrophyID == updatedTrophy.TrophyID && a.PlayerNIC == updatedTrophy.PlayerNIC);

               if (trophyFromDb == null)
               {
                   return NotFound();
               }

               trophyFromDb.BaseFee= updatedTrophy.BaseFee;
               _db.SaveChanges();
            
            return RedirectToAction("Details");


        }

    }
}

ESports/Controllers/TrophyTeamController.cs
using ESports.Data;
using ESports.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;

namespace ESports.Controllers
{
    public class TrophyTeamController : Controller
    {
        private readonly AppDbContext _db;
   

        public TrophyTeamController(AppDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var userid = User.FindFirstValue(ClaimTypes.NameIdentifier);

            return View();
        }
        public IActionResult Add(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var trophyFromDb = _db.Trophies.Find(id);
            
           

            if (trophyFromDb == null)
            {
              
                return NotFound();
            }
            List<SelectListItem> teamsList = new List<SelectListItem>();

            var teamsFromDb = _db.Teams;
            teamsList.Add(new SelectListItem
            {
                Text = "Select The Team",
                Value = ""
            });

            foreach(var team in teamsFromDb)
            {
                teamsList.Add(new SelectListItem
                {
                    Text = team.Name,
                    Value = team.Id
                });
            }
            ViewBag.Teams = teamsList;

            AddTrophyTeamViewModel addTrophyTeam = new AddTrophyTeamViewModel();
            addTrophyTeam.trophy = trophyFromDb;
            addTrophyTeam.teams = teamsList;

            return View(addTrophyTeam);
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(AddTrophyTeamViewModel obj)
        {
            var dobj = obj;
            if (ModelState.IsValid)
            {
                var team = new TrophyTeam()
                {
                    TeamId = obj.trophyTeam.TeamId,
                    TrophyID = obj.trophy.Id,
                    MaxPrice = obj.trophyTeam.MaxPrice,

                };
              
                _db.TrophyTeams.Add(team);
                _db.SaveChanges();

                return RedirectToAction("Index", "Trophy");

            }
               
            return View();
        }
    }
}

ESports/Views/Trophy/Close.cshtml
@model Trophy


<form method="post">
    <div class="border p-3 mt-4">
        <h2 class="text-primary">Close Trophy</h2>
        <hr />
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" disabled/>
        </div>
          <div class="mb-3">
            <label asp-for="Venue">Event Venue</label>
            <input asp-for="Venue" class="form-control" disabled/>
        </div>
         <div class="mb-3">
            <label asp-for="StartDate">Event Starting Date</label>
            <input asp-for="StartDate" class="form-control" type="datetime" disabled/>
        </div>
          <div class="mb-3">
            <label asp-for="EndDate">Event Ending Date</label>
            <input asp-for="EndDate" class="form-control" type="datetime" disabled/>
        </div>
         <div class="mb-3">
            <label asp-for="ClosingDate"></label>
            <input asp-for="ClosingDate" class="form-control" type="datetime" disabled/>
        </div>
          <div class="mb-3">
           <button type="submit" class="btn btn-primary" style="width:150px">Close</button>
           <a  asp-controller="Trophy" asp-action="Index" class="btn btn-secondary" style="width:150px">Back</a>
        </div>
        
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

ESports/Views/Trophy/Create.cshtml
@model Trophy


<form method="post">
    <div class="border p-3 mt-4">
        <h2 class="text-primary">Create Trophy</h2>
        <hr />
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" required />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
          <div class="mb-3">
            <label asp-for="Venue">Event Venue</label>
            <input asp-for="Venue" class="form-control"  required/>
             <span asp-validation-for="Venue" class="text-danger"></span>
        </div>
         <div class="mb-3">
            <label asp-for="StartDate">Event Starting Date</label>
            <input asp-for="StartDate" class="form-control" type="datetime" required/>
            <span asp-validation-for="StartDate" class="text-danger"></span>
        </div>
          <div class="mb-3">
            <label asp-for="EndDate">Event Ending Date</label>
            <input asp-for="EndDate" class="form-control" type="datetime"  required/>
             <span asp-validation-for="EndDate" class="text-danger"></span>
        </div>
         <div class="mb-3">
            <label asp-for="ClosingDate"></label>
            <input asp-for="ClosingDate" class="form-control" type="datetime" required/>
            <span asp-validation-for="ClosingDate" class="text-danger"></span>
        </div>
          <div class="mb-3">
           <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
           <a  asp-controller="Trophy" asp-action="Index" class="btn btn-secondary" style="width:150px">Back</a>
        </div>
        
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

ESports/Views/Trophy/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model TrophyDetailsViewModel
<h1 class="text-primary mt-4 mb-4">@Model.trophy.Name Details</h1>

<table class="table table-striped">
    <tbody>
        <tr>
            <th scope="row">Name</th>
            <td>@Model.trophy.Name</td>
        </tr>
        <tr>
            <th scope="row">Venue</th>
            <td>@Model.trophy.Venue</td>
        </tr>
        <tr>
            <th scope="row">Closing date</th>
            <td>@Model.trophy.ClosingDate</td>
        </tr>
    </tbody>
</table>
<h3 class="text-primary mt-5 mb-4">Regisered players</h3>
<table class="table table-striped">
    <thead>
        <tr class="table-success">
            <th scope="col">
                Name
            </th>
            <th scope="col">
                Age
            </th>
            <th scope="col">
                Role
            </th>
            <th scope="col">
                Hand
            </th>
            <th scope="col">
                Team
            </th>
            <th scope="col">
                Base Fee
            </th>
            @if (User.IsInRole("admin"))
            {
                <th scope="col">
                    Actions
                </th>
            }
            @if (User.IsInRole("user"))
            {
                <th scope="col">
                    Bid
                </th>
            }

        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model.registrations)
        {
            <tr class="table-dark">
                <td>
                    <a asp-controller="Player" asp-action="Profile" asp-route-nic=@item.PlayerNIC>
                        @item.PlayerFName @item.PlayerLName
                    </a>

                </td>
                <td>@item.PlayerAge</td>
                <td>@item.PlayerRole</td>
                <td>@item.PlayerHand</td>
                <td>@item.CurrentTeam</td>
                <td>@item.BaseFee</td>
                @if (User.IsInRole("admin"))
                {
                    <td width="30%">
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Trophy" asp-action="Update" asp-route-id="@item.PlayerNIC" asp-route-tid="@item.TrophyID" class="btn btn-primary mx-1">
                                Update Base Fee
                            </a>

                        </div>
                    </td>
                }
                @if (User.IsInRole("user"))
                {
                    <td>
                        <form method="post">
                            
                            <input asp-for=bidValue id="bidValue" type="number" min=@item.BaseFee value=@item.BaseFee />
                            <input type="submit" asp-controller="Bid" asp-action="Create" class="btn btn-primary mx-1" value="Bid for player"/>
                            <input type="hidden" asp-for=team value=@User.Identity.Name/>
                            <input type="hidden" asp-for=playerNIC value=@item.PlayerNIC/>
                            <input type="hidden" asp-for=trophyId value=@Model.trophy.Id/>
                        </form>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>

ESports/Views/Trophy/Edit.cshtml
@model Trophy



<form method="post">
    <div class="border p-3 mt-4">
        <h2 class="text-primary">Update Trophy</h2>
        <hr />
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
          <div class="mb-3">
            <label asp-for="Venue">Event Venue</label>
            <input asp-for="Venue" class="form-control" />
             <span asp-validation-for="Venue" class="text-danger"></span>
        </div>
         <div class="mb-3">
            <label asp-for="StartDate">Event Starting Date</label>
            <input asp-for="StartDate" class="form-control" type="datetime"/>
            <span asp-validation-for="StartDate" class="text-danger"></span>
        </div>
          <div class="mb-3">
            <label asp-for="EndDate">Event Ending Date</label>
            <input asp-for="EndDate" class="form-control" type="datetime" />
             <span asp-validation-for="EndDate" class="text-danger"></span>
        </div>
         <div class="mb-3">
            <label asp-for="ClosingDate"></label>
            <input asp-for="ClosingDate" class="form-control" type="datetime"/>
            <span asp-validation-for="ClosingDate" class="text-danger"></span>
        </div>
          <div class="mb-3">
           <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
           <a  asp-controller="Trophy" asp-action="Index" class="btn btn-secondary" style="width:150px">Back</a>
        </div>
        
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}

ESports/Views/Trophy/Index.cshtml
@using ESports.Models
@model IEnumerable<Trophy>

@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class=" row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Trophy List</h2>
        </div>
        @if (User.IsInRole("admin"))
        {
            <div class="col-6 text-end">
                <a asp-controller="Trophy" asp-action="Create" class="btn btn-info">Add New Trophy</a>
        </div>
        }
    </div>
</div>

<table class="table table-bordered table-striped" style="width: 100%">
    <thead>
        <tr class="table-secondary">
            <th hidden>
                Trophy ID
            </th>
            <th>
                Trophy Name
            </th>
            <th>
                Event Venue
            </th>
            <th>
                Event Starting Date
            </th>
            <th>
                Event Ending Date
            </th>
            <th>
                Registration/Bidding Closing Date
            </th>
            @if (User.IsInRole("admin"))
            {
                 <th>
                Actions
            </th>
            }
           
            <th>
                Status
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var obj in Model)
        {
            <tr class="table-dark">
                <td hidden>
                    @obj.Id
                </td>
                <td width="20%">
                    <a asp-controller="Trophy" asp-action="Details" asp-route-tid=@obj.Id>

                    @obj.Name
                    </a>
                </td>
                <td width="10%">
                    @obj.Venue
                </td>
                <td width="15%">
                    @obj.StartDate
                </td>
                <td width="15%">
                    @obj.EndDate
                </td>
                <td width="20%">
                    @obj.ClosingDate
                </td>
                @if (User.IsInRole("admin"))
                {
                     <td width="100%">
                    @if (obj.isClosed)
                        {
                              <div class="w-75 btn-group" role="group">
                        <a  class="btn-warning btn">No Actions Allow</a>
                        
                    </div>
                        }
                    else
                    {
                         <div class="w-100 btn-group" role="group">
                          <a asp-controller="TrophyTeam" asp-action="Add" asp-route-id="@obj.Id" class="btn btn-primary mx-1">
                            Add Team
                        </a>
                        <a asp-controller="Trophy" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-light mx-1">
                            Edit
                        </a>
                         <a asp-controller="Trophy" asp-action="Close" asp-route-id="@obj.Id" class="btn btn-danger mx-2">
                            Close
                        </a>
                    </div>
                    }

                    
                    
                </td>
                }

                @if (User.Identity.IsAuthenticated)
                {
                     @if (obj.isClosed)
                {
                     <td width="30%">
                    <div class="w-75 btn-group" role="group">
                        <a  class="btn-warning btn">Closed</a>
                        
                    </div>
                </td>
                }
                 @if (!obj.isClosed)
                {
                      <td width="30%">
                    <div class="w-75 btn-group" role="group">
                        <a class="btn-success btn">Open</a>
                        
                    </div>
                </td>
                }
                }
                else
                {
                     @if (obj.isClosed)
                {
                     <td width="30%">
                    <div class="w-75 btn-group" role="group">
                        <a  class="btn-warning btn">Closed</a>
                        
                    </div>
                </td>
                }
                 @if (!obj.isClosed)
                {
                      <td width="30%">
                    <div class="w-75 btn-group" role="group">
                        <a asp-controller="Registration" asp-action="Enroll" class="btn-primary btn" asp-route-tid=@obj.Id>Register</a>
                        
                    </div>
                </td>
                }
                }

               

              
            </tr>
        }
    </tbody>
</table>
 
                      

ESports/Views/Trophy/Update.cshtml
@model TrophyRegistration



<form method="post" asp-action="UpdatePOST">
    <input asp-for="PlayerNIC" hidden />
    <input asp-for="TrophyID" hidden />
    <div class="border p-3 mt-4">
        <h2 class="text-primary">Update Player Base Fee</h2>
        <hr />
        <div asp-validation-summary="All"></div>
        <div class="mb-3">
            <label asp-for="PlayerFName">First Name</label>
            <input asp-for="PlayerFName" class="form-control"  />
        </div>
          <div class="mb-3">
            <label asp-for="PlayerLName">Last Name</label>
            <input asp-for="PlayerLName" class="form-control"/>
        </div>
         <div class="mb-3">
            <label asp-for="PlayerAge">Age</label>
            <input asp-for="PlayerAge" class="form-control" />
        </div>
          <div class="mb-3">
            <label asp-for="PlayerHand">Player Hand</label>
            <input asp-for="PlayerHand" class="form-control" />
        </div>
            <div class="mb-3">
            <label asp-for="PlayerRole">Player Role</label>
            <input asp-for="PlayerRole" class="form-control"  />
        </div>
         <div class="mb-3">
            <label asp-for="BaseFee"></label>
            <input asp-for="BaseFee" class="form-control" type="number"/>
            <span asp-validation-for="BaseFee" class="text-danger"></span>
        </div>
          <div class="mb-3">
           <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
           <a  asp-controller="Trophy" asp-action="Details" class="btn btn-secondary" style="width:150px">Back</a>
        </div>
        
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial"/>
    }
}