ESports/Controllers/PlayerController.cs
using ESports.Data;
using ESports.Models;
using Microsoft.AspNetCore.Mvc;

namespace ESports.Controllers
{
    public class PlayerController : Controller
    {
        private readonly AppDbContext _db;
        public PlayerController(AppDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var playerList = _db.TrophyRegistrations.ToList().DistinctBy(a => a.PlayerNIC).ToList();


            if (playerList != null)
            {
                return View(playerList);

            }
            return RedirectToAction("Index", "Trophy");
        }

        public IActionResult Profile(string nic)
        {
            var player = _db.TrophyRegistrations.Where(a => a.PlayerNIC == nic).ToList();
            List<Trophy> appliedTrophies = new List<Trophy>();

            foreach (var item in player)
            {
                var trophy = _db.Trophies.Find(item.TrophyID);
                if (trophy != null)
                {
                    appliedTrophies.Add(trophy);
                }
            }

            ProfileViewModel profiles = new ProfileViewModel();
            profiles.registrations = player;
            profiles.trophies = appliedTrophies;

            return View(profiles);
        }
    }
}

ESports/Controllers/ReportController.cs
using ESports.Data;
using ESports.Models;
using Microsoft.AspNetCore.Mvc;

namespace ESports.Controllers
{
    public class ReportController : Controller
    {
        private readonly AppDbContext _db;

        public ReportController(AppDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            ReportViewModel reportData = new ReportViewModel();
            reportData.TeamList = _db.Teams.ToList();
            reportData.TrophyList = _db.Trophies.ToList();
            reportData.PlayerList = _db.TrophyRegistrations.ToList().DistinctBy(a => a.PlayerNIC).ToList();
            return View(reportData);
        }
    }
}

ESports/Controllers/TeamController.cs
using ESports.Data;
using ESports.Models;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace ESports.Controllers
{
    public class TeamController : Controller
    {
        private readonly AppDbContext _db;

        public TeamController(AppDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var userid = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var teams = _db.TrophyTeams.Where(a => a.TeamId == userid).ToList();

            var listOfTrophies = new List<Trophy>();

            foreach(var team in teams)
            {
                var trophyData = _db.Trophies.First(a => a.Id == team.TrophyID);
                listOfTrophies.Add(trophyData);
            }

            TrophyTeamTrophyListViewModel addTrophyTeam = new TrophyTeamTrophyListViewModel();
            addTrophyTeam.trophy = listOfTrophies;
            addTrophyTeam.trophyTeam = teams;

            return View(addTrophyTeam);
        }

        
    }
}

ESports/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ESports</title>
    <link rel="stylesheet" href="~/css/bootswatch.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ESports.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
     <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ESports</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">
       
        <li class="nav-item">
         <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
         <a class="nav-link text-light" asp-area="" asp-controller="Trophy" asp-action="Index">Trophy</a>
        </li>
        <li class="nav-item">
        <a class="nav-link text-light" asp-area="" asp-controller="Player" asp-action="Index">Players</a>
        </li>
         @if (User.IsInRole("user"))
                        {
                            
<li class="nav-item">
        <a class="nav-link text-light" asp-area="" asp-controller="Team" asp-action="Index">Registered Trophies</a>
        </li>
                        }
                        @if (User.IsInRole("admin"))
                        {
                             <li class="nav-item">
        <a asp-controller="Report" asp-action="Index" class="nav-link text-light">View Reports</a>
    </li>
                        }

      </ul>
    <ul class="navbar-nav">
                        @if (User.IsInRole("admin"))
                        {
                             <li class="nav-item">
        <h5  class="text-dark">Hello @User.Identity.Name!</h5>
    </li>
                        }
                        @if (User.IsInRole("user"))
                        {
                             <li class="nav-item">
        <h5  class="text-dark">Hello Team @User.Identity.Name!</h5>
    </li>
                        }


                        @if (User.Identity.IsAuthenticated)
{
   
    <li class="nav-item">
        <form id="logoutForm" class="form-inline" asp-area="" asp-controller="UserAuthentication" asp-action="Logout">
            <button id="logout" type="submit" class="nav-link btn btn-link text-dark">Logout</button>
        </form>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link text-light" id="register" asp-area="" asp-controller="UserAuthentication" asp-action="Registration">Register a Team</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-light" id="login" asp-area="" asp-controller="UserAuthentication" asp-action="Login">Login</a>
    </li>
}


</ul>
    </div>
  </div>
</nav>

      
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class=" footer text-muted bg-dark">
        <div class="container">
            &copy; 2022 - ESports - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>